# version: '3.8'

services:
  app:
    build: .
    image: jre17-alpine:1.0.0
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:+UseG1GC -Dcom.sun.management.jmxremote
